spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost }
      port: ${REDIS_PORT:6379}
  jpa:
    generate-ddl: true
    open-in-view: false
  datasource:
    hikari:
      schema: library_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS app_schema
      connection-timeout: 10000
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    url: jdbc:postgresql://${DATA_BASE_HOST:localhost}:${DATA_BASE_PORT:5432}/library_db

app:
  redis:
    enable: ${APP_CACHE_ENABLE:true}
  cache:
    cacheType: redis
    cache-names:
      - bookByCategoryName
      - booksByAuthorAndTitle
    caches:
      bookByCategoryName:
        expire: ${CACHE_BY_CATEGORY_NAME_EXPIRE:10m}
      booksByAuthorAndTitle:
        expire: ${CACHE_BY_AUTHOR_AND_TITLE_EXPIRE:10m}

server:
  port: 8080
  host: http://localhost